# Generated by Django 4.0.5 on 2022-09-16 08:54

from django.db import migrations, models
import startpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0003_dish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[(startpage.models.Category.Status['Active'], 'Active'), (startpage.models.Category.Status['Deleted'], 'Deleted'), (startpage.models.Category.Status['Inactive'], 'Inactive')], default=startpage.models.Category.Status['Active'], max_length=100),
        ),
    ]
