# Generated by Django 4.0.5 on 2022-09-16 08:58

from django.db import migrations, models
import startpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0004_alter_category_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[(startpage.models.Category.Status['Active'], 1), (startpage.models.Category.Status['Deleted'], 2), (startpage.models.Category.Status['Inactive'], 3)], default=startpage.models.Category.Status['Active'], max_length=100),
        ),
    ]
