# Generated by Django 4.0.5 on 2022-09-16 08:59

from django.db import migrations, models
import startpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0005_alter_category_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('Active', startpage.models.Category.Status['Active']), ('Deleted', startpage.models.Category.Status['Deleted']), ('Inactive', startpage.models.Category.Status['Inactive'])], default=startpage.models.Category.Status['Active'], max_length=100),
        ),
    ]
